/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("dev.geco.gsit.java-conventions")
}

dependencies {
    api(project(":core"))
    api(project(":v1_17"))
    api(project(":v1_17_1"))
    api(project(":v1_18"))
    api(project(":v1_18_2"))
    api(project(":v1_19"))
    api(project(":v1_19_1"))
    api(project(":v1_19_3"))
    api(project(":v1_19_4"))
    api(project(":v1_20"))
    api(project(":v1_20_2"))
    api(project(":v1_20_3"))
}

description = "dist"
