/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "GSit"
include(":core")
include(":mcv1_19_4")
include(":mcv1_20_3")
include(":v1_19_3")
include(":v1_19_1")
include(":v1_18_2")
include(":mcv1_19")
include(":mcv1_17")
include(":v1_19")
include(":v1_20_3")
include(":v1_17")
include(":mcv1_20")
include(":mcv1_19_3")
include(":mcv1_20_2")
include(":mcv1_18_2")
include(":mcv1_19_1")
include(":v1_19_4")
include(":v1_17_1")
include(":v1_20")
include(":v1_20_2")
include(":mcv1_17_1")
include(":mcv1_18")
include(":v1_18")
