/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("dev.geco.gsit.java-conventions")
}

dependencies {
    api(project(":mcv1_19_1"))
}

description = "v1_19_1"
